### ISSUE TITLE
Unexpected argument 

### ISSUE THREAD

**Issue by berzentine** [Shivanshu-Gupta/Visual-Question-Answering#1]
File "main.py", line 72, in main
    model = VQAModel(mode=config['mode'], **config['model']['params'])
  File "/home/multimodal/LSTM_CNN/Visual-Question-Answering/vqa.py", line 137, in __init__
    extract_img_features=extract_img_features, features_dir=features_dir)
TypeError: __init__() got an unexpected keyword argument 'extract_img_features

**Comment by BA3000** [comment]
The problem is caused by line 65 of `main.py`:

```python
config['model']['params']['exatract_img_features'] = 'preprocess' in config['data']['images'] and config['data']['images']['preprocess']
```

noticed that `'exatract_img_features'` ? Change it to `'extract_img_features'` should fix your problem.

**Comment by Alex-HaochenLi** [comment]
it has a spelling mistake. check it!

**Comment by Shivanshu-Gupta** [comment]
Fixed, thanks for pointing out.
