### ISSUE TITLE
Size mismatch

### ISSUE THREAD

**Issue by SatyamGaba** [Shivanshu-Gupta/Visual-Question-Answering#3]
<img width="767" alt="Capture" src="https://user-images.githubusercontent.com/37405020/76153777-0260bd80-6086-11ea-851e-d075c90bb188.PNG">

**Comment by dhruvsharma15** [comment]
In vqa.py under the class Image Embedding, remove 'not' from line number 89.

Earlier:
def forward(self, image, image_ids):
        # Pdb().set_trace()
        if not self.extract_features:
            image = self.extractor(image)

After changing:
def forward(self, image, image_ids):
        # Pdb().set_trace()
        if self.extract_features:
            image = self.extractor(image)

Also, make sure to set your extract_img_features=True in the VQA class. It worked then for me.

**Comment by SatyamGaba** [comment]
There are 100 other issues with this repository. I recommend you not using it. I implemented the same, you may check it on my Github profile.
